version: '3.8'

services:
  mock-register:
    container_name: cuscal-mock-register
    image: rkona/cuscal-mock-register
    ports: 
      - "7000:7000"
      - "7001:7001"
      - "7006:7006"
    extra_hosts:
    - "mock-data-holder:host-gateway"
    - "127.0.0.1:mock-register"
    - "127.0.0.1:mock-data-holder"
    - "127.0.0.1:mssql"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - IssuerUri=https://accc.dev.cuscal.com.au:7000/idp
      - JwksUri=https://accc.dev.cuscal.com.au:7000/idp/.well-known/openid-configuration/jwks
      - TokenUri=https://acccpost.dev.cuscal.com.au:7001/idp/connect/token
      - IdentityServerTokenUri=https://acccpost.dev.cuscal.com.au:7001/idp/connect/token
      - IdentityServerUrl=https://accc.dev.cuscal.com.au:7000/idp
      - IdentityServerIssuer=https://accc.dev.cuscal.com.au:7000/idp      
    healthcheck:
      test: wget --no-check-certificate --no-verbose --spider https://localhost:7006/health || exit 1
      timeout: 5s
      interval: 5s
      retries: 50      
    depends_on:
      mssql:
        condition: service_healthy
  mssql:
    container_name: sql1
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pa{}w0rd2019
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S . -U sa -P "Pa{}w0rd2019" -Q "SELECT 1" || exit 1 
      timeout: 10s
      interval: 10s
      retries: 10    
